IGNORE = [
  'colorado', 'denver', 'boulder', 'new york city',
  'backend developer', 'software engineer', 'full-stack developer', 'remote ok',
  'frontend developer', 'redwood city', 'san francisco bay area',
  'mobile developer', 'software development', 'san francisco', 'qa engineer',
  'management', 'software engineering', 'washington dc', 'backend development', 'backend developer',
  'full stack development', 'software architect', 'irvine', 'seattle', 'designer', 'tdd',
  'boulder county', 'test driven development',
  'software development','linux','san francisco','engineering manager','curriculum development',
  'teaching / instruction','project management','salt lake city','ui/ux designer','operations',
  'broomfield','stockholm','frontend development','windows azure','remote','unit testing','finance/accounting',
  'marketing','colorado springs','automation','western europe','austin','fort collins','product manager',
  'customer service','raleigh','software architecture','gui development','managing and motivating teams',
  'express.js','material design','swagger','telemetry','product design','hls video streaming','denver county',
  'microsoft windows xp 7 8 8.1 10','microsoft visual studio','3d modeling','animation','adobe photoshop',
  'functional testing','software development management','software engineering/development','philadelphia',
  'china','web applications','problem solving','jira','continuous deployment','slovakia','czech republic',
  'message queues','content creator','agile','system administration','system implementation',
  'software integrations','quality assurance','enterprise systems integration','customer experience',
  'continuous integration','mountain view','social impact','boise','indianapolis','microsoft windows',
  'littleton','gainesville','enterprise resource management (erp)','servers','mvc framework','cyber security',
  'security testing','system security','websockets','test','public speaking','customer success','devops engineering',
  'devops architect','growth hacker','innovation & growth','growth strategy and execution','growth','growth hacking',
  'sales','toronto','salesforce administrator','california','salesforce developer','software design',
  'communication skills','salesforce','tucson','ux/ui architecture','agile methodology',
  'rapid ux/ui prototyping','ux/ui','ohio','app/product ux/ui designer and architect','ux/ui design',
  'englewood','drafting','estimating','cost accounting','data architecture','data warehouse',
  'scrum','web development','boston','financial','api design','costing','hbase','security','leadership',
  'sensors','unix','wireless','professional communication','technical support','qa testing','saas',
  'algorithms & data structures','manual testing','automated software testing','london','front-end development',
  'devops', 'web technologies', 'internet of things', 'mobile application development', 'cloud computing',
  'computer programming - java/c++/python', 'ios design', 'mapreduce', 'mobile', 'android design',
  'technical leadership', 'mobile development', 'telecommunications', 'sketch', 'mobile application design',
  'ibm rational rose', 'ibm rational tools', 'software testing', 'systems engineer', 'database programming and administration',
  'database and systems design', 'postman', 'metrics', 'database management', 'netsuite', 'audio engineering',
  'relational databases', 'scripting languages', 'hci/ ux design', 'scalable systems', 'hci', 'ui/ux design',
  'cross platform mobile development', 'javascript frameworks', 'xcode', 'product development', 'product management',
  'rational clear quest', 'rdbms', 'full time', 'los angeles', 'internship', 'palo alto', 'chicago', 'san mateo',
  'silicon valley', 'cofounder','san jose','santa monica','united states','cambridge','computer science','statistics',
  'menlo park','computer vision','new york','full-stack web development (node/redux/react)','user experience design',
  'natural language processing','embedded systems','web application development','atlanta','algorithms','github',
  'business analyst','data visualization','sunnyvale','programming','software','object oriented programming','scalability',
  'berkeley','san diego','dallas','test automation','burlingame','playa vista','multithreading','hardware engineer',
  'start-ups','web services','restful api','project manager','los altos','microsoft azure','network security',
  'android sdk','mentoring','responsive design','engineering','baltimore','headquarters','back-end development',
  'web design','debugging','engineering management','miami','networking','agile software develoment','computer graphics',
  'orange county','mathematics','virtualization - linux containers','des plaines','park city','microsoft excel',
  'web application security','portland','tempe','user interface design','milwaukee','functional programming','linux kernel',
  'infrastructure','bellevue','predictive analytics','user researcher','coding','europe','information security',
  'documentation','grpc','user interface','android studio','cloud services','system design','linux system administration',
  'pittsburgh','networking & tcp/ip','costa mesa','richmond','attention to detail','enterprise software','qa automation',
  'lincoln','mathematical algorithms/data analysis','tornado','team player','santa clara','application development',
  'business development','culver city','cto','open source software','vancouver','healthcare','team lead',
  'firmware','montreal','software defined radio (sdr)','riga','cassandra','detroit','site reliability engineering',
  'finance','presentation skills','retention','digital marketing','graphic design','marketing manager','minneapolis','software implementation',
  'data security','venice beach','jupyter notebooks','bdd/tdd','security engineering','product strategy',
  'object classification','tampa','san leandro','apex visualforce','oakland','e-commerce','concurrency',
  'plano','operating systems','able to work independently','earth','api development','video','integration testing',
  'dev ops','parallel processing','education','organizational skills','robotics','payment processing',
  'developer evangelism','technical writing','electrical engineering','monitoring','problem solving skills',
  'test cases','seo','game development','new jersey','durham','tableau','probability & statistics',
  'operations manager','docker swarm','reverse engineering','front-end/full-stack (ui-angularjs-js-nodejs)',
  'vulnerability assessment','account manager','restful api development','google adwords and analytics','retail',
  'quantitative analysis','performance tuning','email marketing','analytics & reporting','information technology',
  'mobile application testing','certified scrum master','sdk','natural language understanding','emr','north carolina',
  'payments','south carolina','computer vision, machine learning, robotics, deep learning','ann arbor','saratoga',
  'intel dpdk','numpy','houston','information architecture', 'georgia', 'programming: 3p apis & libraries',
  'warehouse management system', 'payment gateways',
  'cloud architecture', 'pci compliance', 'wms', 'santa barbara', 'west hollywood', 'frontend engineering',
  'database schema design', 'keras', 'shell scripting', 'iot', 'pandas', 'user experience', 'mechanical engineer',
  'mvc', 'hardware engineering', 'birmingham', 'sales engineering', 'product marketing',
  'client relations', 'design documentation', 'materials science', 'chemistry', 'brooklyn', 'business intelligence',
  'microservice architecture', 'statistical analysis', 'version control',
  'machine learning algorithms, deep learning, artificial neural networks', 'research', 'software engineering manager',
  'embedded firmware development', 'centos', 'frisco', 'speech recognition', 'scaling web applications',
  'bayesian statistics', 'canada', 'delaware', 'encryption', 'hive', '3d graphics', 'product engineering',
  'developer relations', 'developer advocate', 'community evangelism', 'passion for education', 'teaching.',
  'video management software', 'chrome extensions', 'software and infrastructure architecure',
  'descriptive and inferential statistics', 'time series analysis', 'behavioral analytics', 'paas',
  'machine learning and deep learning', 'consumer products', 'ux design - ios phone & tablet', 'ios app design',
  'user experience & conversion optimization', 'server deployment & management', 'anti-ddos', 'beijing', 'madrid',
  'computer engineering', 'testing frameworks', 'shell commands', 'xilinx vivado', 'rtl design', 'vhdl / verilog',
  'rtl digital design', 'cloud computing/saas', 'director of engineering', 'vp of engineering', 'oem relationships',
  'hardware design', 'performance metrics analysis / optimization', 'database marketing', 'radius',
  'wireless technology', 'wireless networking', 'c/c++ and java coding', 'algorithmic research', 'provisioning',
  'sysadmin', 'device drivers', 'additive manufacturing', 'design for manufacturing', 'fluid mechanics', 'physics',
  'manufacturing', 'phoenixville', 'asana', 'payment systems', 'leading engineering teams', 'engineering leadership',
  'senior software developer', 'network routing: ospf/ rip', 'computer networking', 'service design',
  'software development engineering in test (sdet)', 'etl development', 'etl testing', 'dbms', 'airflow', 'analytics',
  'mobile payments', 'pci security compliancy', 'analytical/critical thinking skills', 'data structures',
  'people management and leadership', 'object-oriented design', 'ipsec vpn', 'ipsec', 'google compute engine',
  'artificial neural networks', 'valencia', 'messaging', 'mobile product management', 'service oriented architecture (soa)',
  'cinematography', 'video production', 'video editing', 'creative director', 'visual designer', 'google adwords',
  'facebook advertising', 'cloud based infrastructure', 'oo design', 'restful web services', 'technology management',
  'fuzzing', 'ida pro', 'penetration testing', 'gnu radio', 'simd programming', 'sabre', 'cissp', 'chandler',
  'san antonio', 'multitasker; team player; hard worker', 'cross-platform development', 'aosp', 'infrastructure automation',
  'production support', 'automated testing', 'ability to work in a fast paced environment', 'willingness to learn',
  'python and c++ (cross-language programming)', 'rf engineering', 'team leadership', 'planning',
  'real-time operating systems rtos', 'linear algebra', 'signal processing', 'research and development',
  'research and data analysis', 'investigative reporting', 'investigative research', 'writing', 'team building',
  'application / platform architecture', 'ehr', 'haverhill', 'nashville', 'room', 'dagger2', 'grafana',
  'google cloud dataflow', 'distributed computing', 'vertica', 'rtp', 'tcp/ip', 'voip telecommunications',
  'backend', 'search engine marketing (sem)', 'conversion optimization', 'gtm', 'google tag manager',
  'search engine optimization', 'ecommerce', 'travel technology', 'travel', 'design of experiments', 'user acquisition',
  'escalation management', 'interaction design', 'semantic search', 'content writing', 'b2b marketing',
  'performance marketing', 'reinforcement learning', 'compliance', 'regulatory compliance', 'qa management', 'mclean',
  'computer programming', 'unix/linux', 'systems architecture & design', 'systems (hardware/software) architecture',
  'systems architect', 'mailchimp', 'robot framework', 'adtech', 'garden grove', 'sacramento', 'bend', 'pair programming',
  'embedded software development', 'mobile or handset testing', 'hardware', 'mvw', 'wpf', 'http tcp udp ip', 'dns',
  'video streaming', 'middleware', 'sas', 'solutions architecture', 'solution architect', 'fort lauderdale',
  'smart home technology', 'home automation systems', 'video / vfx production', 'virtual reality', 'algebraic geometry',
  'generalized logic systems - topos theory', 'cellular automata', 'parallel computing', 'sass/less/stylus',
  'oracle mysql nosql big data', 'creative problem solving', 'medical devices', 'computer and electrical engineering',
  'programming: c, python, java.', 'javascript/jquery/d3/highcharts', 'html5 css3 sass bootstrap javascript jquery',
  'sql server integration services (ssis)', 'full-stack web development (node/redux/react/graphql)',
  'smart', 'learning and development', 'orm', 'ionic framework', 'phonegap/cordova', 'stripe payments', 'team management',
  'product requirements', 'burlington', 'tysons', 'berlin', 'data', 'ubuntu', 'react/mobx', 'westminster',
  'gitflow', 'confluence', 'customer relationship management', 'python(django), ruby(rubyonrails), java(play)',
  'marketing management', 'product and channel marketing', 'demand generation', 'customer acquisition',
  'marketing strategy', 'restaurant technology', 'cold calling', 'buffalo', 'software qa methodologies',
  'selenium webdriver', 'informational retrieval systems', 'information retrieval', 'recommendation systems', 'gce',
  'aws/map reduce/spark', 'noida', 'vr development', 'samsung gear vr', 'software architecture and design',
  'agile transformation', 'analytical skills', 'sales strategy and management', 'api testing', 'rs232', 'i2c', 'spi',
  'business analysis', 'protocol buffers', 'browserstack', 'calabash', 'robotium', 'columbus',
  'caffe torch7 theano', 'theano', 'spinnaker', 'push notifications',
  'marina del rey', 'venice', 'social media marketing', 'event planning', 'hospitality', 'social media', 'turkey',
  'ukraine', 'russia', 'developer', 'workshop design and facilitation', 'solutions engineering', 'cross-functional collaboration',
  'software product demonstrations', 'management consulting', 'presentation design', 'solution design', 'helpdesk support',
  'zendesk', 'organization',
  'community strategy', 'community engagement', 'community management', 'hr', 'benefits administration', 'hr management',
  'compensation and benefits', 'h.r.', 'concord', 'data communication bus protocol/interconnect', 'microcontrollers',
  'event sourcing', 'maryland', 'sanic', 'soap/rest (web services)', 'software programming', 'user generated content / ugc',
  'seo / ppc management', 'ppc', 'template creation', 'cms', 'invision', 'teamwork', 'user testing', 'front end programming',
  'support', 'india', 'bengaluru', 'apache airflow', 'aws (ec2/emr/s3/redshift)', 'pyspark (core spark and spark sql)',
  'git & github', 'sql/mysql/postgresql', 'user growth', 'canvas', 'south america', 'automation ci/cd',
  'large-scale distributed systems', 'nomad', 'marathon', 'mesos', 'orchestration', 'filesystems', 'spring boot',
  'gpu computing', 'restful apis', 'http protocol', 'openstack', 'sms/mms', 'freeswitch', 'video encoding', 'midwest',
  'issue tracking', 'test management', 'mentorship', 'root cause analysis', 'text mining', 'server virtualization and containerization',
  'google app engine', 'prometheus', 'electronic medical record', 'saltstack', 'scipy', 'pig', 'electronic medical records',
  'dicom', '*nix', 'mercurial', 'computational geometry', 'excellent oral and written communication', 'content management',
  'writting', 'highly organized', 'etcd', 'financial trading', 'account management', 'crm', 'sales manager', 'equities trading',
  'electronic trading', 'trading systems', 'financial exchanges', 'trading', 'real time bidding', 'html5/css javascript ruby on rails mysql',
  'survival analysis', 'logistic regression', 'startups', '3d rendering', 'flight dynamics', 'flight control systems', 'motion planning',
  'control systems', 'web application frameworks', 'embedded software', 'santa ana', 'virtual machines', 'server cluster management',
  'multiprocessing', 'openmvg', '3d reconstruction', 'quantum espresso', 'transfer learning', 'classification', 'etl pipelines',
  'special capital region of jakarta', 'gcp', 'reliability engineering',
  'cql (cassandra query language)', 'deployment', 'oop', 'facial recognition', 'singapore', 'periscope', 'qa testing / automation',
  'manual qa', 'kiev', 'leadership and team inspiration', 'district of columbia', 'aws cloudformation', 'cape town', 'pasadena',
  'wifi (802.11a/b/g/n/ac) and bluetooth hw', 'wifi', 'bluetooth low energy', 'workflow management',
  'regression testing', 'server and software architecture', 'automation testing using selenium', 'test scripts',
  'accessability testing', 'apache tomcat', 'iis', 'security research', 'blogging', 'deep learning with tensorflow, keras',
  'nosql dbs - mongodb cassandra redis neo4j', 'agile software development', 'wireshark', 'network protocols', 'chatbots',
  'kazan', 'ux/ui developer/designer', 'applications engineering', 'machine perception', 'continuos integration', 'florida',
  'orlando', 'commercial loans', 'data products', 'business insights', 'credit analysis', 'financial markets', 'firebug',
  'karma', 'jmeter', 'junit', 'grpahic design', 'cicd', 'aws/ec2/elb/s3/vpc', 'openvz', 'recruiting',
  'application deployment (docker)', 'code review', 'cross-browser compatibility', 'wcag', 'looker', 'google sheets',
  'woopra analytics', 'technical & customer support', 'map reduce', 'cultural heritage', 'digital humanities',
  'educational technology', 'storm', 'cincinnati', 'reactive programming', 'amazon ecs', 'convolutional neural networks',
  'machine vision', 'image processing', 'educational technologies', 'ux design', 'user experience research',
  'usability testing', 'massachusetts', 'one signal', 'apiary', 'digital ocean', 'encyption', 'mvvm architecture',
  'mobile/web: android rest apis json xml', 'realm mobile database', 'itunes connect / testflight / carshlytics',
  'mixpanel', 'statistical modeling', 'financial modeling', 'cross-functional leadership & collaboration', 'business strategy',
  'ui/ux engineering', 'app/product ux/ui senior engineer', 'website development/design', 'spray', 'individual contributor',
  'a/b testing', 'angular js, ajax, bootstrap, c, c++, core java, html, javascript, jquery, mysql,sql.',
  'api, systems documentation, production engineering support documentation, ui', 'contract',
  'database: mysql, nosql (mongo db, h base, redis, postgre sql, graph based: gremin)', 'ember cli',
  'location based services', 'microservices  core java react.js spring', 'search', 'seo/sem',
  'machine learning: supervised/unsupervised models(decision tree, naive bayes, knn, clu',
  'machine learning, data science, python, perl, r', 'machine learning data science python r', 'mysql/postgres'
].freeze

FUZZY_IGNORE = [/theano-keras-scikit/].freeze
