NORMALIZE = {
  'ios' => ['ios development', 'iphone', 'swift/objective c/ios/xcode', 'objective-c', 'swift',
    'ios development / objective-c (cocoa touch)', 'ios swift'],
  'data engineering' => ['big data', 'data scientist', 'data science',
    'big data analytics', 'data mining', 'big data analytics (nosql)', 'data pipelines', 'etl'],
  'artificial intelligence' => ['machine learning', 'neural networks', 'unsupervised machine learning', 'ai', 'deep learning',
    'deep learning with tensorflow', 'deep neural networks', 'nerual networks'],
  'microservices' => ['distributed systems', 'soa'],
  'javascript' => ['es6', 'ecmascript 6', 'javacript', 'es2016', 'es2016+', 'javascript es6'],
  'rails' => ['backend rails development', 'experienced rails developer', 'ruby', 'ruby on rails'],
  'android' => ['android application development', 'android development', 'andriod', 'android framework',
    'java (android sdk + eclipse + android studio)'],
  'java' => ['jvm', 'j2ee. spring. hibernate. maven.', 'java j2ee', 'java/javaee', 'rxjava'],
  'css' => ['cascading style sheet (css)', 'css preprocessors (sass / less / etc.)'],
  'react.js' => ['reactjs', 'react js', 'react/flux', 'react/graphql', 'react/redux'],
  'node.js' => ['nodejs', 'nodejs/ express/ es6'],
  'angular.js' => ['angular 2', 'angularjs', 'angular'],
  'elixir' => ['phoenix'],
  'vue.js' => ['vuejs'],
  'ethereum' => ['solidity', 'solidity (ethereum)', 'smart contracts'],
  'blockchain' => ['cryptocurrencies', 'cryptocurrency trading'],
  'aws' => ['aws cloud services', 'amazon web services'],
  'rest' => ['rest apis', 'restful services'],
  'mean stack' => ['mean', 'mean full stack developer'],
  'php' => ['html/css/php/mysql'],
  'go' => ['go', 'go (golang)', 'golang', 'go (programming language)'],
  'postgresql' => ['postgres'],
  'matlab' => ['matlab/simulink', 'matlab/octave'],
  'c#' => ['.net', '.net core', '.net framework c# asp.net mvc', 'c sharp (c#)', 'c#.net', 'asp.net',
    'microsoft .net'],
  'backbone.js' => ['backbone.marionette'],
  'assembly language' => ['assembly language (evm)', 'assembler'],
  'bash' => ['bash scripting'],
  'c' => ['c programming', 'embedded c/c++'],
  'django' => ['django-rest-framework', 'python/django/flask'],
  'docker' => ['docker / docker compose / kubernetes', 'docker containers'],
  'graph ql' => ['graphql/apollo'],
  'hadoop' => ['hadoop mapreduce', 'hadoop/hive/spark/scala/mllib'],
  'html' => ['html 5', 'html+css', 'html/css/javascript', 'html5', 'html5 & css3', 'hmtl'],
  'c++' => ['modern c++'],
  'python' => ['phython', 'python (sklearn)'],
  'sass' => ['scss', 'scss / sass'],
  'git' => ['source control: git'],
  'unity' => ['unity3d', 'unreal'],
  'sql server' => ['t-sql', 'microsoft sql server'],
  'google cloud' => ['cloud services google/firebase/aws/openshift']
}
